train_path: datasets/ADE20K/images/training/*.jpg
train_label_path: datasets/ADE20K/annotations/training/*.png
val_path: datasets/ADE20K/images/validation/*.jpg
val_label_path: datasets/ADE20K/annotations/validation/*.png
color_dict: datasets/ADE20K/color_dict.txt
dimensions: [128, 128]
channels: 3
n_classes: 150
ppm_output_channels: 512
pooling_sizes: [1, 2, 3, 6]
strides: 1
batch_size: 16
epochs: 5
learning_rate: 0.01
model_path: models/PSP50